fix(CucumberReportPublisher):setNotFailingStatuses for jenkins in CucumberReportPublisher
jenkinsci/cucumber-reports-plugin pull request #379
Opened 2020-10-16 08:03 UTC by AyushRawat1

1: adding the set not failing statuses to this class so that we can set this feature from jenkins like for other features we do mergeFeaturesWithRetest: true,
sortingMethod: 'ALPHABETICAL' in the jenkins

2: this is how we will use it through jenkins

def s = ["SKIPPED"] as Set
always {
cucumber fileIncludePattern: "${env.BUILD_NUMBER}/build/cucumber/bbt_*.json",
reportTitle: "${params.title}${env.TEST_ENVIRONMENT}/${params.cucumber_tag}",
notFailingStatues: s
}

2020-10-24 23:01 UTC, damianszczepanik requested changes

2020-10-24 23:01 UTC, damianszczepanik commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +    public void setNotFailingStatues(Set<Status> notFailingStatues) {
where this value comes from ?

2020-10-26 05:48 UTC, AyushRawat1 commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +    public void setNotFailingStatues(Set<Status> notFailingStatues) {
the values will come from when we set these not failing statues from the jenkins for the other repo where we are using this plugin 

def s = ["SKIPPED"] as Set
always {
cucumber fileIncludePattern: "${env.BUILD_NUMBER}/build/cucumber/bbt_*.json",
reportTitle: "${params.title}${env.TEST_ENVIRONMENT}/${params.cucumber_tag}",
mergeFeaturesWithRetest: true,
sortingMethod: 'ALPHABETICAL',
notFailingStatues: s
}

like this as we do for other fields like sortingMethod and mergeFeaturesWithRetest

2020-10-28 20:39 UTC, damianszczepanik commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +    public void setNotFailingStatues(Set<Status> notFailingStatues) {
OK, how about setting it via GUI? When editing job configuration?

2020-10-29 13:41 UTC, AyushRawat1 commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +    public void setNotFailingStatues(Set<Status> notFailingStatues) {
so that's the update you talking about in .jelly file right??

2020-10-30 13:24 UTC, AyushRawat1 commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +    public void setNotFailingStatues(Set<Status> notFailingStatues) {
So you are talking about adding in the jelly file right?? Sure will do that too

2020-11-04 06:25 UTC, AyushRawat1 commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +    public void setNotFailingStatues(Set<Status> notFailingStatues) {
@damianszczepanik can you please review it again i have added the jelly functionality as well, Thanks

2020-11-07 15:56 UTC, damianszczepanik requested changes

2020-11-07 15:56 UTC, damianszczepanik commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +    private void addNotFailingStatuesToBuildReport(Run<?, ?> build, FilePath workspace, TaskListener listener, Configuration configuration, Set<Status> setToAdd) throws InterruptedException, IOExcept
is all exceptions required?

2020-11-07 15:56 UTC, damianszczepanik commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +      Set<net.masterthought.cucumber.json.support.Status> set = new HashSet<>();
why full package is provided here?

2020-11-07 15:56 UTC, damianszczepanik commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +          log(listener, String.format("Adding %d not Failing Statues(s)", notFailingStatues.size()));
Why the message is provided With Capital Case ?

2020-11-07 15:56 UTC, damianszczepanik commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +      for (Status item : setToAdd) {
statussesToAdd

2020-11-07 15:56 UTC, damianszczepanik commented on src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-setNotFailingStatues.html
> +    notFailingStatues: setNotFailingStatues</p>
new line missing

2020-11-07 15:56 UTC, damianszczepanik commented on src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-setNotFailingStatues.html
> +    def setNotFailingStatues = ["SKIPPED"....] as Set
nice

2020-11-07 15:56 UTC, damianszczepanik commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +      public String key;
what is the key used for ?

2020-11-11 13:41 UTC, AyushRawat1 commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +    private void addNotFailingStatuesToBuildReport(Run<?, ?> build, FilePath workspace, TaskListener listener, Configuration configuration, Set<Status> setToAdd) throws InterruptedException, IOExcept
removed IllegalArgumentException

2020-11-11 13:42 UTC, AyushRawat1 commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +      Set<net.masterthought.cucumber.json.support.Status> set = new HashSet<>();
because we have a same name static class in here

2020-11-11 13:42 UTC, AyushRawat1 commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +      for (Status item : setToAdd) {
done

2020-11-11 13:42 UTC, AyushRawat1 commented on src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-setNotFailingStatues.html
> +    notFailingStatues: setNotFailingStatues</p>
added

2020-11-11 13:43 UTC, AyushRawat1 commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +      public String key;
removed it was not getting used

2020-11-11 13:43 UTC, AyushRawat1 commented on src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
> +          log(listener, String.format("Adding %d not Failing Statues(s)", notFailingStatues.size()));
changed the format

2020-11-14 21:35 UTC, damianszczepanik commented
Code looks good, some checks are not - take a look

2020-12-03 20:47 UTC, damianszczepanik commented
Honestly I have no idea, try to update this commit and update it so that should trigger building process one more time

2020-12-11 06:17 UTC, AyushRawat1 commented
> Honestly I have no idea, try to update this commit and update it so that should trigger building process one more time

Hi @damianszczepanik still does not work, Can you reference someone on your team who can help me with this jelly configuration builds??.
Thanks

2020-12-23 16:26 UTC, AyushRawat1 commented
> Honestly I have no idea, try to update this commit and update it so that should trigger building process one more time

i did rerun and did not work, can you help me by referencing someone so they can help me out with the jelly configuration failures

Thanks

2021-01-14 05:59 UTC, AyushRawat1 commented
@damianszczepanik just a follow up on my comments above, Thanks

2021-01-16 11:31 UTC, damianszczepanik commented
https://app.shippable.com/github/jenkinsci/cucumber-reports-plugin/runs/113/1/console it provides details about the error which of course means that you have never ever build this code locally :(

2021-01-18 06:35 UTC, AyushRawat1 commented
Hi @damianszczepanik 
Thanks for the update i did build it in the local and found out the issue, Solved it 
All the checks are completed 
Thanks

2021-01-19 21:00 UTC, damianszczepanik commented
How did you check and how ?

2021-01-20 09:23 UTC, AyushRawat1 commented
@damianszczepanik can you review the PR again

2021-01-20 09:26 UTC, AyushRawat1 commented
@damianszczepanik so i build the project in local and it was unable to parse the jelly config file 
Turns out i was missing a ">"  
field="notFailingStatues" here i put it back and all checks passed

2021-01-20 09:28 UTC, AyushRawat1 commented
@damianszczepanik is the code alright now ? i mean is it ready to merge or something else needs to be done from my side?

2021-01-25 19:06 UTC, AyushRawat1 commented
@damianszczepanik just a follow up on latest commit

2021-01-26 21:35 UTC, damianszczepanik commented
I don't see any confirmation you have tested your code. Last error proves you don't and I don't want to merge untested code.

2021-01-27 10:59 UTC, AyushRawat1 commented
@damianszczepanik can you tell me the command to publish the pulgin in local so that i can import my update of the plugin and test in out in my the repo i am working in 
is that how it should be tested??

2021-02-11 06:14 UTC, AyushRawat1 commented
@damianszczepanik can you tell me the commands to publish the repo in local and then i can import the jar in my folder and test 
or if there is a better way how you do it you can tell?
thanks

2021-02-11 06:45 UTC, damianszczepanik commented
mvn install

2022-11-02 23:22 UTC, closed without merging